name: CI Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with GCC
      run: |
        g++ -std=c++17 -O2 -o myapp main.cpp
        ./myapp

